### ISSUE TITLE
GenericRestLookupController fails to initialize if endpoint.properties is unavailable.

### ISSUE THREAD

**Issue by nblair** [UW-Madison-DoIT/rest-proxy#12]
Following the instructions in the README to `@ComponentScan` the edu.wisc.my.restproxy package results in my application failing to start because I don't have a resource named endpoint.properties.

`@PropertySource` is typically placed on `@Configuration` classes rather than directly on controllers.

**Comment by timlevett** [comment]
This is gone, so delete?

**Comment by nblair** [comment]
Yep!
