### ISSUE TITLE
Rename project to rest-proxy

### ISSUE THREAD

**Issue by nblair** [UW-Madison-DoIT/rest-proxy#23]
Feedback from the development community has presented us a new name:

> rest-proxy

The library doesn't require that we proxy only json, and the -service suffix leads to some confusion about what the deliverable artifact is.

Acceptance Criteria:
- repository is renamed to https://github.com/UW-Madison-DoIT/rest-proxy
- artifactId changes to rest-proxy.

**Comment by paulerickson** [comment]
Do we prefer to actually rename the repo or just port to a new one and deprecate?  Either way, I'll leave it you you & Tim, or whomever has admin rights.

**Comment by timlevett** [comment]
I'm curious to try the rename to see what happens if you try to hit the old remote :)

**Comment by paulerickson** [comment]
@timlevett BitBucket asks you if you'd like to leave a redirect when you delete a repo, so hopefully GitHub can do the same

**Comment by timlevett** [comment]
Looks like they are in place and it "just works". no prompt. #knowledge
