### ISSUE TITLE
rest-proxy-core release is not public

### ISSUE THREAD

**Issue by hamdrew** [UW-Madison-DoIT/rest-proxy#34]
When attempting to add the rest-proxy-core:2.0.0 dependency to my maven project, I get the following error:

> `Could not transfer artifact edu.wisc.my.restproxy:rest-proxy-core:jar:2.0.0 from/to code.doit-uw-releases (https://code.doit.wisc.edu/maven/content/repositories/uw-releases/): Access denied to: https://code.doit.wisc.edu/maven/content/repositories/uw-releases/edu/wisc/my/restproxy/rest-proxy-core/2.0.0/rest-proxy-core-2.0.0.jar , ReasonPhrase:Forbidden.`

I do not see any stable releases for rest-proxy-core on maven central nor our private Nexus repository. I do see SNAPSHOT builds for 2.1.0 in Nexus.

**Comment by timlevett** [comment]
Interesting, looks like converting it to gradle may have broken it? Looking at http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22edu.wisc.my.restproxy%22%20AND%20a%3A%22json-proxy-service%22

@paulerickson ?

**Comment by paulerickson** [comment]
My bad - I made a job on our build box just to run tests and publish to [Sonar](http://ia-builds.doit.wisc.edu:9000/dashboard/index/62594), but I stopped short of the `uploadArchives` task assuming you were doing that on the my-tools instance.  Looks like there's no json-proxy-\* or rest-proxy-\* build there, though (maybe it went away with the name change?), so I can add it to our existing build.

**Comment by timlevett** [comment]
We currently do not have a build task for `rest-proxy` as we are not currently using it.

**Comment by hamdrew** [comment]
We are! :fist:

**Comment by paulerickson** [comment]
Okay, the build is updated and #35 open to stabilize the version.  I don't know what happened to 2.**0**.0... it looks a lot like I skipped right over it, although I can't remember or imagine why.

**Comment by paulerickson** [comment]
After much config-wrangling, 2.1.1 is released and available in maven central:

https://repo1.maven.org/maven2/edu/wisc/my/restproxy/
