### ISSUE TITLE
Rest proxy encodes parameters and doesn't append them properly

### ISSUE THREAD

**Issue by timlevett** [UW-Madison-DoIT/rest-proxy#44]
Use case, google custom search.

```
wiscedusearch.uri=http://ajax.googleapis.com/ajax/services/search/web?v=1.0&rsz=10&start=0&cx=removed
wiscmaillookup.username=
wiscmaillookup.password=
wiscmaillookup.attributes=
wiscmaillookup.method=
```

URL: `localhost:8080/api/wiscedusearch/?q=test`

Resulting redirect to: http://ajax.googleapis.com/ajax/services/search/web?v=1.0&rsz=10&start=0&cx=removed?q%3Dtest

Really its 2 issues:
1) If you have params in your uri, rest-proxy doesn't recognized that and has 2 ?
2) the = is encoded to %3

**Comment by timlevett** [comment]
@vertein your last pull fix this issue too?

**Comment by vertein** [comment]
Yeah, pr https://github.com/UW-Madison-DoIT/rest-proxy/pull/42 fixed issue https://github.com/UW-Madison-DoIT/rest-proxy/issues/41 which looks the same as issue https://github.com/UW-Madison-DoIT/rest-proxy/issues/44
