### ISSUE TITLE
Expose health status

### ISSUE THREAD

**Issue by apetro** [UW-Madison-DoIT/rest-proxy#48]
`rest-proxy` is well positioned to watch the proxied requests and note some ways they fail.
- Notice when the proxied endpoint returns a 5XX status code, or fails to connect at all.
- Log.
- Expose as its own healthcheck web service, maybe that reports back the endpoints, their most recent exercise timestamp, and the status code or lack of connection that happened on that most recent exercise.

(Backlogged as [MUMMNG-2675](https://jira.doit.wisc.edu/jira/browse/MUMMNG-2675).)

This could drive an AngularJS administrative front end that shows the status of the proxies.
Could also feed e.g. Nagios monitoring.

**Comment by timlevett** [comment]
That sounds fun. lets do that. :+1:

**Comment by timlevett** [comment]
resolved
